spring:

  datasource:
    url: jdbc:sqlserver://azure01-server.database.windows.net:1433;database=sampledb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: shwetapandey
    password: admin@123
     
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8181
  